"""
ai_analysis.py
Provides CFO Chat, Board Memo, and NL Query functionality.
Works offline using rule-based templates derived from session_state data.
If ANTHROPIC_API_KEY or OPENAI_API_KEY is set in environment, attempts
to use the LLM for richer responses – failure falls back gracefully.
"""
from __future__ import annotations

import os
from typing import Optional

import numpy as np
import pandas as pd


# ─────────────────────────── offline templates ───────────────────

def _fmt(v: float, unit: str = "PLN") -> str:
    if abs(v) >= 1_000_000:
        return f"{v/1_000_000:.2f}M {unit}"
    if abs(v) >= 1_000:
        return f"{v/1_000:.1f}K {unit}"
    return f"{v:.2f} {unit}"


def offline_cfo_summary(bs: dict, flags: list[dict], filename: str) -> str:
    if not bs:
        return "No data analyzed yet. Please upload and analyze a trial balance file."

    ta = bs.get("total_assets", 0)
    tl = bs.get("total_liabilities", 0)
    te = bs.get("total_equity", 0)
    diff = bs.get("difference", 0)
    errors = [f for f in flags if f.get("type") == "error"]
    warnings = [f for f in flags if f.get("type") == "warning"]

    balance_status = "✅ Balanced" if abs(diff) < 1 else f"⚠️ Imbalance: {_fmt(diff)}"
    leverage = tl / te if te != 0 else float("inf")

    lines = [
        f"## CFO Summary – {filename}",
        "",
        f"**Total Assets:** {_fmt(ta)}",
        f"**Total Liabilities:** {_fmt(tl)}",
        f"**Total Equity:** {_fmt(te)}",
        f"**Balance Check:** {balance_status}",
        f"**Debt/Equity Ratio:** {leverage:.2f}x",
        "",
        f"**Data Quality:** {len(errors)} error(s), {len(warnings)} warning(s)",
    ]
    if errors:
        lines.append("\n**Critical Issues:**")
        for e in errors[:5]:
            lines.append(f"- 🔴 {e['message']}")
    if warnings:
        lines.append("\n**Warnings:**")
        for w in warnings[:5]:
            lines.append(f"- 🟡 {w['message']}")

    lines += [
        "",
        "---",
        "*Generated by Financial Analyzer – offline mode. Connect an LLM API for AI-powered analysis.*",
    ]
    return "\n".join(lines)


def offline_board_memo(bs: dict, flags: list[dict], filename: str) -> str:
    if not bs:
        return "No data available for memo generation."

    ta = bs.get("total_assets", 0)
    tl = bs.get("total_liabilities", 0)
    te = bs.get("total_equity", 0)
    diff = bs.get("difference", 0)

    return f"""# Board of Directors – Financial Memo

**Subject:** Trial Balance Review – {filename}  
**Prepared by:** Financial Analyzer System  
**Classification:** Internal

---

## Executive Summary

The trial balance has been processed and mapped to the reporting structure.

| Metric | Value |
|---|---|
| Total Assets | {_fmt(ta)} |
| Total Liabilities | {_fmt(tl)} |
| Total Equity | {_fmt(te)} |
| Balance Difference | {_fmt(diff)} |

## Key Observations

1. **Balance Sheet Integrity:** {"The balance sheet is in balance." if abs(diff) < 1 else f"An imbalance of {_fmt(diff)} was detected and requires investigation."}
2. **Leverage Position:** Debt-to-equity ratio of {(tl/te if te != 0 else float("inf")):.2f}x {"indicates manageable leverage." if tl/te < 2 else "may warrant attention."}
3. **Data Quality:** {sum(1 for f in flags if f["type"] == "error")} data quality issue(s) identified.

## Recommendations

- Review unmapped accounts for completeness
- Confirm inter-company eliminations if applicable
- Reconcile any balance sheet difference before period close

---

*This memo was generated automatically. AI-enhanced analysis available with LLM API integration.*
"""


def offline_nl_query(query: str, bs: dict, mapp_df: Optional[pd.DataFrame]) -> str:
    """Simple rule-based NL query responder."""
    if not bs:
        return "Please analyze a file first."

    q = query.lower().strip()
    ta = bs.get("total_assets", 0)
    tl = bs.get("total_liabilities", 0)
    te = bs.get("total_equity", 0)
    diff = bs.get("difference", 0)

    if any(k in q for k in ["total asset", "aktywa", "assets"]):
        return f"**Total Assets:** {_fmt(ta)}"

    if any(k in q for k in ["liabilit", "pasywa", "zobowiązan"]):
        return f"**Total Liabilities:** {_fmt(tl)}"

    if any(k in q for k in ["equity", "kapita", "własny"]):
        return f"**Total Equity:** {_fmt(te)}"

    if any(k in q for k in ["balance", "różnic", "bilans"]):
        return f"**Balance Difference:** {_fmt(diff)} ({'balanced' if abs(diff) < 1 else 'not balanced'})"

    if any(k in q for k in ["largest", "biggest", "top", "największ"]):
        if mapp_df is not None and not mapp_df.empty:
            top = mapp_df.nlargest(5, "persaldo")[["account_number", "account_name", "persaldo"]]
            rows = "\n".join(f"- **{r.account_number}** {r.account_name}: {_fmt(r.persaldo)}" for r in top.itertuples())
            return f"**Top 5 accounts by net balance:**\n{rows}"

    if any(k in q for k in ["unmapped", "niezmappow", "heuristic"]):
        if mapp_df is not None and not mapp_df.empty:
            n = len(mapp_df[mapp_df["mapping_status"] == "heuristic"])
            return f"**Heuristically mapped accounts:** {n} ({n/len(mapp_df)*100:.1f}%)"

    return (
        "I can answer questions about: total assets, liabilities, equity, "
        "balance difference, top accounts, and mapping status.\n\n"
        f"*Your query: '{query}' – try rephrasing or connect an LLM API for free-form queries.*"
    )


# ─────────────────────────── LLM integration (optional) ──────────

def try_llm_query(prompt: str) -> Optional[str]:
    """
    Attempt to call an LLM API. Returns None if unavailable.
    Supports: OpenAI (OPENAI_API_KEY), Anthropic (ANTHROPIC_API_KEY).
    """
    api_key = os.environ.get("OPENAI_API_KEY") or os.environ.get("ANTHROPIC_API_KEY")
    if not api_key:
        return None

    # Anthropic
    if os.environ.get("ANTHROPIC_API_KEY"):
        try:
            import anthropic
            client = anthropic.Anthropic()
            msg = client.messages.create(
                model="claude-3-haiku-20240307",
                max_tokens=1024,
                messages=[{"role": "user", "content": prompt}],
            )
            return msg.content[0].text
        except Exception as e:
            return f"[LLM error: {e}]"

    # OpenAI fallback
    if os.environ.get("OPENAI_API_KEY"):
        try:
            import openai
            client = openai.OpenAI()
            resp = client.chat.completions.create(
                model="gpt-3.5-turbo",
                messages=[{"role": "user", "content": prompt}],
                max_tokens=1024,
            )
            return resp.choices[0].message.content
        except Exception as e:
            return f"[LLM error: {e}]"

    return None
